//Items

StartupEvents.registry('item', (event) => {

    //Catalogs
    event.create('submerged:catalog_catalog').displayName('Catalog: Catalog').maxStackSize(1).glow(true)
    
    event.create('submerged:catalog_hats').displayName('Catalog: Hats').maxStackSize(1).glow(true)
    event.create('submerged:catalog_ducks').displayName('Catalog: Ducks').maxStackSize(1).glow(true)
    event.create('submerged:catalog_simple_blocks').displayName('Catalog: Simple Blocks').maxStackSize(1).glow(true)
    event.create('submerged:catalog_flares').displayName('Catalog: Flares').maxStackSize(1).glow(true)

    //Items
    event.create('submerged:unloaded_flare')
    event.create('submerged:stone_key')
    event.create('submerged:copper_key')
    event.create('submerged:iron_key')
    event.create('submerged:netherite_key')
    event.create('submerged:ceramic_solid_coal_bucket')
    event.create('submerged:solid_coal_bucket')
    event.create('submerged:key_mold').tag(['c:molds/key', 'casting:molds'])
    event.create('submerged:mesh_mold').tag(['c:molds/mesh', 'casting:molds'])
    event.create('submerged:quartz_enriched_gold').tag(['c:ingots/quartz_enriched_gold', 'c:ingots'])
    event.create('submerged:infused_alloy')
    event.create('submerged:ancient_lens')
    event.create('submerged:blank_spawn_egg')
    event.create('submerged:raw_ancient_debris').tag(['c:raw_materials/ancient_debris', 'c:raw_materials'])
    event.create('submerged:ancient_debris_dust').tag(['c:dusts/ancient_debris', 'c:dusts'])
    event.create('submerged:prismarine_crystal_activator')
    event.create('submerged:porcelain_clay')
    event.create('submerged:wooden_key')

    event.create('submerged:basic_storage_component').tag('submerged:basic_storage_components').texture('ae2:item/cell_component_1k')
    event.create('submerged:advanced_storage_component').tag('submerged:advanced_storage_components').texture('ae2:item/cell_component_4k')
    event.create('submerged:elite_storage_component').tag('submerged:elite_storage_components').texture('ae2:item/cell_component_16k')
    event.create('submerged:ultimate_storage_component').tag('submerged:ultimate_storage_components').texture('ae2:item/cell_component_64k')

    event.create('submerged:logic_processor').tag('submerged:logic_processors').texture('ae2:item/logic_processor')
    event.create('submerged:calculation_processor').tag('submerged:calculation_processors').texture('ae2:item/calculation_processor')
    event.create('submerged:engineering_processor').tag('submerged:engineering_processors').texture('ae2:item/engineering_processor')

    colors.forEach(color => {
        event.create(`submerged:${color}_terracotta_rocks`).tag('submerged:terracotta_rocks')
        event.create(`submerged:${color}_dirt_pile`).tag('submerged:dirt_pile')
        event.create(`submerged:${color}_flare`).tag('submerged:flares')
    })

    //Nether Brick Sphere
    event.create('submerged:nether_brick_sphere', 'roomopolis_key')
        .templateId('submerged:spheres/nether_brick')
        .keyBlock('submerged:nether_brick_lock')
        .heightAdjustment(0)
        .frontAdjustment(1)
        .doorLeft(1) 
        .doorRight(1)
        .doorUp(1)
        .doorDown(1)
        .consumeKey(true)
        .removeDoor(true)
        .blocksRequired(false)
        .overrideExistingBlocks(true)
        .tag('submerged:keys/sphere')


    //Nether Portal Sphere
    event.create('submerged:nether_portal_sphere', 'roomopolis_key')
        .templateId('submerged:spheres/nether_portal')
        .keyBlock('#submerged:terracotta_lock')
        .heightAdjustment(0)
        .frontAdjustment(-1)
        .doorLeft(1) 
        .doorRight(1)
        .doorUp(1)
        .doorDown(1)
        .consumeKey(true)
        .removeDoor(true)
        .blocksRequired(false)
        .overrideExistingBlocks(true)
        .tag('submerged:keys/sphere')


    //Prismarine Sphere Keys 
    event.create(`submerged:prismarine_sphere_key`, 'roomopolis_key')
        .templateId(`submerged:spheres/prismarine_sphere`)
        .keyBlock(`#submerged:terracotta_lock`)
        .heightAdjustment(0)
        .frontAdjustment(-1)
        .doorLeft(1) 
        .doorRight(1)
        .doorUp(1)
        .doorDown(1)
        .consumeKey(true)
        .removeDoor(true)
        .blocksRequired(false)
        .overrideExistingBlocks(true)
        .tag('submerged:keys/sphere')

    //Colored Sphere Keys 
    colors.forEach(color => {
        event.create(`submerged:${color}_sphere_key`, 'roomopolis_key')
            .templateId(`submerged:spheres/${color}`)
            .keyBlock(`submerged:${color}_terracotta_lock`)
            .heightAdjustment(0)
            .frontAdjustment(-1)
            .doorLeft(1)
            .doorRight(1)
            .doorUp(1)
            .doorDown(1)
            .consumeKey(true)
            .removeDoor(true)
            .blocksRequired(false)
            .overrideExistingBlocks(true)
            .tag('submerged:keys/sphere_base')
    })

    event.create(`submerged:3x3_pressure_chamber`, 'roomopolis_key')
        .displayName('3x3 Pressure Chamber Key')
        .templateId(`submerged:pressure_chamber/3x3_pressure_chamber`)
        .keyBlock(`submerged:pressure_chamber_controller`)
        .heightAdjustment(1)
        .consumeKey(true)
        .removeDoor(false)
        .blocksRequired(true)
        .overrideExistingBlocks(false)
        .tag('submerged:keys/pressure_chamber')

    event.create(`submerged:4x4_pressure_chamber`, 'roomopolis_key')
        .displayName('4x4 Pressure Chamber Key')
        .templateId(`submerged:pressure_chamber/4x4_pressure_chamber`)
        .keyBlock(`submerged:pressure_chamber_controller`)
        .heightAdjustment(2)
        .consumeKey(true)
        .removeDoor(false)
        .blocksRequired(true)
        .overrideExistingBlocks(false)
        .tag('submerged:keys/pressure_chamber')

    event.create(`submerged:5x5_pressure_chamber`, 'roomopolis_key')
        .displayName('5x5 Pressure Chamber Key')
        .templateId(`submerged:pressure_chamber/5x5_pressure_chamber`)
        .keyBlock(`submerged:pressure_chamber_controller`)
        .heightAdjustment(2)
        .consumeKey(true)
        .removeDoor(false)
        .blocksRequired(true)
        .overrideExistingBlocks(false)
        .tag('submerged:keys/pressure_chamber')

    event.create(`submerged:overworld_altar`, 'roomopolis_key')
        .displayName('Overworld Altar Key')
        .templateId(`submerged:altar`)
        .keyBlock(`naturesaura:nature_altar`)
        .heightAdjustment(2)
        .frontAdjustment(-1)
        .consumeKey(true)
        .removeDoor(false)
        .blocksRequired(true)
        .overrideExistingBlocks(true)
        .sideOnlyPlacement(false)
        .topOnlyPlacement(true)
        .tag('submerged:keys/altar')

})
